---
title: "Simple document"
author: Yuanyuan Zeng
data: 2021-09-16
output: github_document
---
```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(dplyr)
```

## Problem 1

```{r}
# Read and clean the Mr.Trash Wheel sheet
trash_data = 
  read_excel("./Trash_Wheel_Collection_Totals_8_6_19.xlsx", sheet = "Mr. Trash Wheel") %>%     
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  filter(dumpster != "NA") %>% 
  mutate(
    sports_balls = round(sports_balls))

trash_data

# Read and clean the precipitation data for 2018
pre_2018 = (
  read_excel("./Trash_Wheel_Collection_Totals_8_6_19.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
    janitor::clean_names() %>% 
    mutate(year = 2018) %>%  
    relocate(year))

pre_2018

# Read and clean the precipitation data for 2019
pre_2019 = (
  read_excel("./Trash_Wheel_Collection_Totals_8_6_19.xlsx", sheet = "2019 Precipitation", range = "A2:B8") %>% 
    janitor::clean_names() %>% 
    mutate(year = 2019) %>% 
    relocate(year))

pre_2019

# Combine two precipitation data
precipitation_data = (
  bind_rows(pre_2018, pre_2019) %>% 
  mutate(month = month.name[as.numeric(month)])
)

precipitation_data
```
## Problem 2

```{r}
# Clean the data in pols-month.csv
pols_month = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon,  into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = month.name[as.numeric(month)]) %>% 
  pivot_longer(
    prez_gop | prez_dem,
    names_to = "president",
    names_prefix = "prez_",
    values_to = "gop_or_dem") %>% 
  filter( gop_or_dem!=0 ) %>% 
  select(!day & !gop_or_dem) %>% 
  relocate(year, month, president, everything())

pols_month

# Clean the data in snp.csv
snp_df = 
  read_csv("./fivethirtyeight_datasets/snp.csv") %>% 
  mutate(
    date = mdy(date)
  ) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(
    year = ifelse(as.numeric(year)>2049, as.numeric(year)-100, year)
  ) %>% 
  mutate(
    month = month.name[as.numeric(month)]
    ) %>% 
  select(!day) %>% 
  relocate(year) %>% 
  arrange(desc(year))

snp_df

# Clean th unemployment data 
unemployment_df = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv", col_types = "cdddddddddddd") %>% 
  pivot_longer(
    Jan : Dec,
    names_to = "month",
    values_to = "unemployment"
  ) %>% 
  filter(unemployment !="NA") %>% 
  janitor::clean_names() %>% 
  mutate(
    month = match(month, month.abb),
    month = month.name[as.numeric(month)]
  ) %>% 
  arrange(desc(year)) 

unemployment_df

# left join snp into pols data set
pols_snp =
  left_join(pols_month, snp_df, by = c("year","month"))

# left join unemployment into pols_snp 
pols_snp_unemp =
  left_join(pols_snp, unemployment_df, by = c("year", "month"))
```


## Problem 3

```{r}
# Clean the data on popularity of baby names
baby_names = 
  read.csv("./Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>%
  distinct() %>% 
  mutate(
    gender = tolower(gender),
    ethnicity = tolower(ethnicity),
    child_s_first_name = tolower(child_s_first_name)
  )
baby_names

```


